name: Validate

on:
  push:
    branches: [main, evaluation]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: ✅ Project is valid
        run: echo "Validation passed"
